config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products

  resource :cart, only: [ :show ] do
    post "add", path: "add/:id", on: :member
    get :checkout
  end

  resources :orders, only: [ :index, :show, :create ]

  root 'products#index'

end

app/models/cart.rb
class Cart
  attr_reader :items

  def self.build_from_hash hash
    items = if hash["cart"] then
      hash["cart"]["items"].map do |item_data|
        CartItem.new item_data["product_id"], item_data ["quantity"]
        end
      else
       []
    end

    new items
  end

  def initialize items = []
    @items = items
  end

  def add_item product_id
    item = @items.find { |item| item.product_id == product_id }
    if item
      item.increment
    else
      @items << CartItem.new(product_id)
    end
  end

  def empty?
    @items.empty?
  end

  def count
    @items.inject(0){ | cnt, item | cnt + item.quantity}
  end

  def serialize
    items = @items.map do |item|
      {
        "product_id" => item.product_id,
        "quantity" => item.quantity
      }
    end

    {
      "items" => items
    }
  end

  def total_price
    @items.inject(0){ | ttp, item | ttp + item.total_price}
  end
end

app/models/cart_item.rb
class CartItem
  attr_reader :product_id, :quantity

  def initialize product_id, quantity = 1
    @product_id = product_id
    @quantity = quantity
  end

  def increment
    @quantity = @quantity + 1
  end

  def product
    Product.find product_id
  end

  def total_price
    quantity * product.price
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :order_items

  def total_price
    order_items.inject(0) { |sum, item| sum + item.total_price }
  end
end

app/models/order_form.rb
class OrderForm
  include ActiveModel::Model

  attr_accessor :user, :order #creditcard
  attr_writer :cart

  def save
    set_password_for_user
    if valid?
      persist
      true
    else
      false
    end
  end

  def has_errors?
    user.errors.any?
  end

  private

  def valid?
    user.valid?
  end

  def persist
    user.save
    @order = Order.create! user: user

    build_order_items
  end


  def set_password_for_user
    user.password = Digest::SHA1.hexdigest(user.email + Time.now.to_s)[0..8]
  end

  def build_order_items
    @cart.items.each do |item|
      @order.order_items.create! product_id: item.product_id, quantity: item.quantity
    end
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product

  def total_price
    self.quantity * self.product.price
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  validates_presence_of :name, :price
  validates_numericality_of :price
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name, :address, :postal_code, :city, :country
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def initialize_cart
    @cart = Cart.build_from_hash session
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_filter :initialize_cart

  def add
    @cart.add_item params[:id]
    session["cart"] = @cart.serialize
    product = Product.find params[:id]
    redirect_to :back, notice: "Added #{product.name} to cart."
  end

  def show
  end

  def checkout
    @order_form = OrderForm.new user: User.new
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :initialize_cart

  def create
    @order_form = OrderForm.new(
      user: User.new(order_params[:user]),
      cart: @cart
    )

    if @order_form.save
      notify_user
      redirect_to root_path, notice: "Thank you for placing the order."
    else
      render "carts/checkout"
    end
  end

  private

  def notify_user
    @order_form.user.send_reset_password_instructions
    OrderMailer.order_confirmation(@order_form.order).deliver
  end

  def order_params
    params.require(:order_form).permit(
      user: [:name, :email, :city, :country, :postal_code, :address, :phone]
    )
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_filter :initialize_cart

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/application/_cart.html.haml
-if @cart
  %p.navbar-text.navbar-right
    -if @cart.empty?
      Your cart is empty.
    -else
      =link_to "You have #{pluralize @cart.count, "item"}.", cart_path

app/views/application/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Tuts тест-шоп</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Products", products_path %></li>
      </ul>
      <%= render "cart" %>
  </div><!-- /.container-fluid -->
</nav>

app/views/carts/checkout.html.haml
%h1 Checkout

%h2 You are checking out the following products:

%ul
  -@cart.items.each do |item|
    %li
      %em=item.quantity
      =item.product.name
      =number_to_currency item.total_price

%p
  %strong
    Total price:
    =number_to_currency @cart.total_price

=form_for @order_form, url: orders_path do |f|
  =render "orders/errors"

  %h3 Some of your personal details
  =f.fields_for :user, f.object.user do |u|
    .form-group
      %p=u.text_field :name, placeholder: "Name", class: "form-control input-lg"
      %p
        =u.text_field :email, placeholder: "Email", class: "form-control"
        %span.help-block This will help you track your order more effectively.
    .form-group
      .row
        .col-md-6.form-group=u.text_field :address, placeholder: "Address", class: "form-control"
        .col-md-3.form-group=u.text_field :postal_code, placeholder: "Zipcode\Postal code", class: "form-control"
        .col-md-3.form-group=u.text_field :city, placeholder: "City", class: "form-control"
      .form-group=u.country_select :country, { priority_countries: [ "RU", "US", "GB", "TH" ] }, { class: "form-control" }

      .form-group=u.text_field :phone, class: "form-control", placeholder: "Phone"

  %p=f.submit "Place order", class: "btn btn-primary"

app/views/carts/show.html.haml
%h1 Your cart

%table.table.table-hover
  %thead
    %tr
      %th Quantity
      %th Product
      %th Price

  -@cart.items.each do |item|
    %tr
      %td=item.quantity
      %td
        =image_tag item.product.image.thumb
        =link_to item.product.name, item.product
      %td.text.right=number_to_currency item.total_price
  %tfoot
    %tr
      %td.text-right(colspan=3)
        %strong
          Total:
          =number_to_currency @cart.total_price

%p=link_to "Checkout", checkout_cart_path, class: "btn bnt-primary"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tuts</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "nav" %>
<div class="container">
  <%= content_tag :div, notice, class: "bg-success" %>
  <%= content_tag :div, alert, class: "bg-danger" %>
  <%= yield %>

</div>

</body>
</html>

app/views/orders/_errors.html.haml
-if @order_form.has_errors?
  .panel.panel-danger
    .panel-heading
      %h4.panel-title We have found some problems with your data. Please review them.
    .panel-body
      -@order_form.user.errors.full_messages.each do |error|
        %p
          %strong User:
          =error

app/views/products/_form.html.haml
= form_for @product, multipart: true do |f|
  - if @product.errors.any?
    #error_explanation
      %h2= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :price
    = f.text_field :price
  .field
    = f.label :image
    = f.file_field :image
  .actions
    = f.submit 'Save'

app/views/products/edit.html.haml
%h1 Editing product

= render 'form'

= link_to 'Show', @product
\|
= link_to 'Back', products_path

app/views/products/index.html.haml
%h1 Listing products

%table.table.table-hover
  %thead
    %tr
      %th Name
      %th Price
      %th Image
      %th

  %tbody
    - @products.each do |product|
      %tr
        %td= link_to product.name, product
        %td= number_to_currency product.price
        %td= image_tag product.image.thumb
        %td
          = link_to 'Edit', edit_product_path(product)
          = link_to 'Destroy', product, :method => :delete, :data => { :confirm => 'Are you sure?' }

%p= link_to 'New Product', new_product_path, class: "btn btn-primary"

app/views/products/new.html.haml
%h1 New product

= render 'form'

= link_to 'Back', products_path

app/views/products/show.html.haml
%h1= @product.name

%p= number_to_currency @product.price
%p= image_tag @product.image, height:  "300"

%p=link_to "Add to cart", add_cart_path, method: :post, class: "btn btn-primary"

%p
  = link_to 'Edit', edit_product_path(@product)
  \|
  = link_to 'Back', products_path